boot collators bringup updates
NodleCode/chain pull request #537
Opened 2022-03-02 15:56 UTC by rajesh-nodle

Boot collators bringup updates

2022-03-02 20:23 UTC, noisefloors commented on scripts/vnv-boot-collators/init-env.sh
> +export COLLATOR1_OVERALL_SECRET=""
Are these `_SECRET` values items that might be useful to read from the environment?

```
export COLLATOR1_OVERALL_SECRET="${COLLATOR1_OVERALL_SECRET}"
```

The above should allow the value to be populated by a predefined value.

2022-03-02 20:23 UTC, noisefloors commented
Good work, @rajesh-nodle! I left a question above, feel free to ignore if you don't find it valuable.

2022-03-07 08:57 UTC, ETeissonniere requested changes

2022-03-07 08:57 UTC, ETeissonniere commented on node/res/eden.json
> +		"/dns4/node-6904339780776906752-0.p2p.onfinality.io/tcp/14896/p2p/12D3KooWD61umWiWrA1cP3wxWcKAcdPyf7kFMRQxJteWe8SSiU6T"
@rajesh-nodle can you update those to match the most recently deployed nodes on OF?

2022-03-11 08:43 UTC, closed without merging