pallet-staking integration to eden
NodleCode/chain pull request #585
Opened 2022-04-14 10:54 UTC by rajesh-nodle

pallet-staking integration to eden

**Work Completed**

* eden runtime changes.
* node parachain genesis update.
* Sanity test.

**Work in progress**

* Storage migration check
* try-runtime check
* Test with stake reward profiler.

2022-04-18 10:05 UTC, ETeissonniere commented
@rajesh-nodle @aliXsed I'd like us to hold on this until we do our parachain migration

2022-04-18 10:10 UTC, ETeissonniere requested changes

2022-04-18 10:10 UTC, ETeissonniere commented on pallets/staking/src/lib.rs
> +            }
@rajesh-nodle it looks like this PR contains both changes to the staking pallet and code to add it to eden. Shouldn't we break into two separate PRs?

2022-04-18 10:10 UTC, ETeissonniere commented on runtimes/eden/src/constants.rs
> +pub const MILLICENTS: Balance = CENTS / 1_000; // = 100 NANO
I'd like to stay off these variables since they are less clear than the MILLI/NANO/MICRO ones, that's why I had removed them

2022-04-18 10:10 UTC, ETeissonniere commented on runtimes/eden/src/pallets_consensus.rs
>  }
why are you removing this pallet?

2022-07-25 03:33 UTC, simonsso commented on runtimes/eden/src/constants.rs
> +        // const MILLICENTS: Balance = CENTS / 1_000; // = 100 NANO
Remove instead of commenting out.

2022-07-25 03:33 UTC, simonsso commented on runtimes/staking/src/pallets_consensus.rs
> +    pub const DefaultStakingMinStakeSessionSelection: Balance = (3 * 10i32.pow(6)) as Balance * constants::NODL;
I think this is clearer
```suggestion
    pub const DefaultStakingMinStakeSessionSelection: Balance = 3_000_000 as Balance * constants::NODL;
```

2022-07-25 03:33 UTC, simonsso commented on runtimes/staking/src/pallets_consensus.rs
> +    pub const DefaultStakingMinValidatorBond: Balance = (100 * 10i32.pow(3)) as Balance * constants::NODL;
```suggestion
    pub const DefaultStakingMinValidatorBond: Balance = 100_000_000 as Balance * constants::NODL;
```
Likewise

2022-08-02 03:55 UTC, aliXsed commented
@rajesh-nodle can you please move rajesh-nodle:shamb0/feature-eden-staking to NodleCode/chain/feature/eden-staking so we keep the changes in a branch for now and close this PR?

2022-08-03 10:29 UTC, closed without merging