Transaction Sponsorship
NodleCode/chain pull request #767
Opened 2023-08-03 05:28 UTC by aliXsed

[WIP]

2023-08-10 21:11 UTC, ETeissonniere requested changes
Looking good! I left some minor changes and thoughts

2023-08-10 21:11 UTC, ETeissonniere commented on pallets/sponsorship/src/lib.rs
> +		}
I think this extrinsic should reserve `fee_quota.saturating_add(reserve_quota)` to:
1. Avoid spamming of this extrinsic
2. Ensure the sponsor has enough funds available for the limits they are setting themselves

2023-08-10 21:11 UTC, ETeissonniere commented on pallets/sponsorship/src/lib.rs
> +		}
Following the above thought, this would unreserve remaining coins

2023-08-14 01:51 UTC, aliXsed commented on pallets/sponsorship/README.md
> +License: MIT-0
@ETeissonniere I added a brief description here instead

2023-08-14 01:54 UTC, aliXsed commented on pallets/sponsorship/src/benchmarking.rs
> +use frame_system::RawOrigin;
@ETeissonniere `#[allow(unused)]` is still needed when you compile for testing benchmarks:
`cargo test -p pallet-sponsorship --features runtime-benchmarks`

2023-08-14 02:19 UTC, aliXsed commented on support/src/lib.rs
> +}
Done. Thank you for reminding it.

2023-08-14 02:25 UTC, aliXsed commented on runtimes/eden/src/pallets_util.rs
> +}
Yes, open to any suggestions. I have [simplified it](https://github.com/NodleCode/chain/pull/767#:~:text=Verified-,6d2a370,-Merge%20state) so we only have two categories for now. But later when we provide more governance decentralisation we can add a category for governance transactions.

2023-08-14 02:40 UTC, aliXsed commented on pallets/sponsorship/src/lib.rs
> +	}
Good suggestion. Done through https://github.com/NodleCode/chain/pull/767#:~:text=Verified-,0216972,-Merge%20state

2023-08-15 22:47 UTC, ETeissonniere commented on pallets/sponsorship/src/benchmarking.rs
> +use frame_system::RawOrigin;
Oops, got it!

2023-08-29 23:34 UTC, ETeissonniere approved these changes
lgtm. to be merged once the `try-runtime` checks pass

2023-08-30 02:54 UTC, merged